version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/htp-was
permissions:
  - object: /home/ubuntu/htp-was
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: serve.sh
      timeout: 300
      runas: ubuntu
