name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: create .env file
        run: |
          cd ${{ github.workspace }}
          cat << EOF > .env
          OPEN_API_KEY=${{ secrets.OPEN_API_KEY }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
          SERVER_URL=${{ secrets.SERVER_URL }}
          CLIENT_URL=${{ secrets.CLIENT_URL }}
          JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }}
          EOF
          chmod 644 .env

      - name: zip codes
        run: tar cvfz ./htp-was.tar.gz .env *

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./htp-was.tar.gz s3://htp-github/was/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name htp-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name htp-was
          --s3-location bucket=htp-github,bundleType=tgz,key=was/htp-was.tar.gz
